/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as acknowledgmentLogSol from "./AcknowledgmentLog.sol";
export type { acknowledgmentLogSol };
import type * as announcementLogSol from "./AnnouncementLog.sol";
export type { announcementLogSol };
import type * as documentRegistrySol from "./DocumentRegistry.sol";
export type { documentRegistrySol };
export type { RoleManager } from "./RoleManager";
