/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AnnouncementLog__factory } from "./AnnouncementLog__factory";
export { IRoleManager__factory } from "./IRoleManager__factory";
