/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AcknowledgmentLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acknowledge"
      | "announcementLog"
      | "getAcknowledgedAt"
      | "roleManager"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Acknowledged"): EventFragment;

  encodeFunctionData(
    functionFragment: "acknowledge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "announcementLog",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAcknowledgedAt",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acknowledge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announcementLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAcknowledgedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
}

export namespace AcknowledgedEvent {
  export type InputTuple = [
    announcementId: BigNumberish,
    student: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    announcementId: bigint,
    student: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    announcementId: bigint;
    student: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AcknowledgmentLog extends BaseContract {
  connect(runner?: ContractRunner | null): AcknowledgmentLog;
  waitForDeployment(): Promise<this>;

  interface: AcknowledgmentLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acknowledge: TypedContractMethod<
    [announcementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  announcementLog: TypedContractMethod<[], [string], "view">;

  getAcknowledgedAt: TypedContractMethod<
    [announcementId: BigNumberish, student: AddressLike],
    [bigint],
    "view"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acknowledge"
  ): TypedContractMethod<[announcementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "announcementLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAcknowledgedAt"
  ): TypedContractMethod<
    [announcementId: BigNumberish, student: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Acknowledged"
  ): TypedContractEvent<
    AcknowledgedEvent.InputTuple,
    AcknowledgedEvent.OutputTuple,
    AcknowledgedEvent.OutputObject
  >;

  filters: {
    "Acknowledged(uint256,address,uint256)": TypedContractEvent<
      AcknowledgedEvent.InputTuple,
      AcknowledgedEvent.OutputTuple,
      AcknowledgedEvent.OutputObject
    >;
    Acknowledged: TypedContractEvent<
      AcknowledgedEvent.InputTuple,
      AcknowledgedEvent.OutputTuple,
      AcknowledgedEvent.OutputObject
    >;
  };
}
