/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcknowledgmentLog } from "./AcknowledgmentLog";
export type { IAnnouncementLog } from "./IAnnouncementLog";
export type { IRoleManagerAck } from "./IRoleManagerAck";
