/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AnnouncementLog {
  export type AnnouncementStruct = {
    contentHash: BytesLike;
    category: string;
    targetGroup: string;
    timestamp: BigNumberish;
    publisher: AddressLike;
  };

  export type AnnouncementStructOutput = [
    contentHash: string,
    category: string,
    targetGroup: string,
    timestamp: bigint,
    publisher: string
  ] & {
    contentHash: string;
    category: string;
    targetGroup: string;
    timestamp: bigint;
    publisher: string;
  };
}

export interface AnnouncementLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "announcementCount"
      | "getAnnouncement"
      | "getTargetGroup"
      | "publish"
      | "roleManager"
      | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AnnouncementPublished"): EventFragment;

  encodeFunctionData(
    functionFragment: "announcementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAnnouncement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetGroup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publish",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "announcementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnnouncement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AnnouncementPublishedEvent {
  export type InputTuple = [
    id: BigNumberish,
    contentHash: BytesLike,
    category: string,
    targetGroup: string,
    publisher: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    contentHash: string,
    category: string,
    targetGroup: string,
    publisher: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    contentHash: string;
    category: string;
    targetGroup: string;
    publisher: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnnouncementLog extends BaseContract {
  connect(runner?: ContractRunner | null): AnnouncementLog;
  waitForDeployment(): Promise<this>;

  interface: AnnouncementLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  announcementCount: TypedContractMethod<[], [bigint], "view">;

  getAnnouncement: TypedContractMethod<
    [id: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput],
    "view"
  >;

  getTargetGroup: TypedContractMethod<[id: BigNumberish], [string], "view">;

  publish: TypedContractMethod<
    [contentHash: BytesLike, category: string, targetGroup: string],
    [bigint],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  verify: TypedContractMethod<
    [id: BigNumberish, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "announcementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAnnouncement"
  ): TypedContractMethod<
    [id: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTargetGroup"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "publish"
  ): TypedContractMethod<
    [contentHash: BytesLike, category: string, targetGroup: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [id: BigNumberish, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AnnouncementPublished"
  ): TypedContractEvent<
    AnnouncementPublishedEvent.InputTuple,
    AnnouncementPublishedEvent.OutputTuple,
    AnnouncementPublishedEvent.OutputObject
  >;

  filters: {
    "AnnouncementPublished(uint256,bytes32,string,string,address,uint256)": TypedContractEvent<
      AnnouncementPublishedEvent.InputTuple,
      AnnouncementPublishedEvent.OutputTuple,
      AnnouncementPublishedEvent.OutputObject
    >;
    AnnouncementPublished: TypedContractEvent<
      AnnouncementPublishedEvent.InputTuple,
      AnnouncementPublishedEvent.OutputTuple,
      AnnouncementPublishedEvent.OutputObject
    >;
  };
}
