/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnnouncementLog } from "./AnnouncementLog";
export type { IRoleManager } from "./IRoleManager";
