/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as acknowledgmentLogSol from "./AcknowledgmentLog.sol";
export * as announcementLogSol from "./AnnouncementLog.sol";
export * as documentRegistrySol from "./DocumentRegistry.sol";
export { RoleManager__factory } from "./RoleManager__factory";
