/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnnouncementLog,
  IAnnouncementLogInterface,
} from "../../../contracts/AcknowledgmentLog.sol/IAnnouncementLog";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getTargetGroup",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnnouncementLog__factory {
  static readonly abi = _abi;
  static createInterface(): IAnnouncementLogInterface {
    return new Interface(_abi) as IAnnouncementLogInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAnnouncementLog {
    return new Contract(address, _abi, runner) as unknown as IAnnouncementLog;
  }
}
