/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AcknowledgmentLog__factory } from "./AcknowledgmentLog__factory";
export { IAnnouncementLog__factory } from "./IAnnouncementLog__factory";
export { IRoleManagerAck__factory } from "./IRoleManagerAck__factory";
