/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoleManagerAck,
  IRoleManagerAckInterface,
} from "../../../contracts/AcknowledgmentLog.sol/IRoleManagerAck";

const _abi = [
  {
    inputs: [],
    name: "STUDENT_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getGroup",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRoleManagerAck__factory {
  static readonly abi = _abi;
  static createInterface(): IRoleManagerAckInterface {
    return new Interface(_abi) as IRoleManagerAckInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoleManagerAck {
    return new Contract(address, _abi, runner) as unknown as IRoleManagerAck;
  }
}
