/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AccessControl } from "./@openzeppelin/contracts/access/AccessControl";
export { AccessControl__factory } from "./factories/@openzeppelin/contracts/access/AccessControl__factory";
export type { IAccessControl } from "./@openzeppelin/contracts/access/IAccessControl";
export { IAccessControl__factory } from "./factories/@openzeppelin/contracts/access/IAccessControl__factory";
export type { ERC165 } from "./@openzeppelin/contracts/utils/introspection/ERC165";
export { ERC165__factory } from "./factories/@openzeppelin/contracts/utils/introspection/ERC165__factory";
export type { IERC165 } from "./@openzeppelin/contracts/utils/introspection/IERC165";
export { IERC165__factory } from "./factories/@openzeppelin/contracts/utils/introspection/IERC165__factory";
export type { AcknowledgmentLog } from "./contracts/AcknowledgmentLog.sol/AcknowledgmentLog";
export { AcknowledgmentLog__factory } from "./factories/contracts/AcknowledgmentLog.sol/AcknowledgmentLog__factory";
export type { IAnnouncementLog } from "./contracts/AcknowledgmentLog.sol/IAnnouncementLog";
export { IAnnouncementLog__factory } from "./factories/contracts/AcknowledgmentLog.sol/IAnnouncementLog__factory";
export type { IRoleManagerAck } from "./contracts/AcknowledgmentLog.sol/IRoleManagerAck";
export { IRoleManagerAck__factory } from "./factories/contracts/AcknowledgmentLog.sol/IRoleManagerAck__factory";
export type { AnnouncementLog } from "./contracts/AnnouncementLog.sol/AnnouncementLog";
export { AnnouncementLog__factory } from "./factories/contracts/AnnouncementLog.sol/AnnouncementLog__factory";
export type { IRoleManager } from "./contracts/AnnouncementLog.sol/IRoleManager";
export { IRoleManager__factory } from "./factories/contracts/AnnouncementLog.sol/IRoleManager__factory";
export type { DocumentRegistry } from "./contracts/DocumentRegistry.sol/DocumentRegistry";
export { DocumentRegistry__factory } from "./factories/contracts/DocumentRegistry.sol/DocumentRegistry__factory";
export type { IRoleManagerDoc } from "./contracts/DocumentRegistry.sol/IRoleManagerDoc";
export { IRoleManagerDoc__factory } from "./factories/contracts/DocumentRegistry.sol/IRoleManagerDoc__factory";
export type { RoleManager } from "./contracts/RoleManager";
export { RoleManager__factory } from "./factories/contracts/RoleManager__factory";
