/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DocumentRegistry__factory } from "./DocumentRegistry__factory";
export { IRoleManagerDoc__factory } from "./IRoleManagerDoc__factory";
