/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoleManagerDoc,
  IRoleManagerDocInterface,
} from "../../../contracts/DocumentRegistry.sol/IRoleManagerDoc";

const _abi = [
  {
    inputs: [],
    name: "PROFESSOR_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRoleManagerDoc__factory {
  static readonly abi = _abi;
  static createInterface(): IRoleManagerDocInterface {
    return new Interface(_abi) as IRoleManagerDocInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoleManagerDoc {
    return new Contract(address, _abi, runner) as unknown as IRoleManagerDoc;
  }
}
