/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DocumentRegistry {
  export type DocumentStruct = {
    fileHash: BytesLike;
    fileName: string;
    targetGroup: string;
    timestamp: BigNumberish;
    publisher: AddressLike;
  };

  export type DocumentStructOutput = [
    fileHash: string,
    fileName: string,
    targetGroup: string,
    timestamp: bigint,
    publisher: string
  ] & {
    fileHash: string;
    fileName: string;
    targetGroup: string;
    timestamp: bigint;
    publisher: string;
  };
}

export interface DocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "documentCount"
      | "getDocument"
      | "register"
      | "roleManager"
      | "verifyDocument"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "documentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "documentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export namespace DocumentRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    fileHash: BytesLike,
    fileName: string,
    targetGroup: string,
    publisher: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    fileHash: string,
    fileName: string,
    targetGroup: string,
    publisher: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    fileHash: string;
    fileName: string;
    targetGroup: string;
    publisher: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: DocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  documentCount: TypedContractMethod<[], [bigint], "view">;

  getDocument: TypedContractMethod<
    [id: BigNumberish],
    [DocumentRegistry.DocumentStructOutput],
    "view"
  >;

  register: TypedContractMethod<
    [fileHash: BytesLike, fileName: string, targetGroup: string],
    [bigint],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  verifyDocument: TypedContractMethod<
    [id: BigNumberish, fileHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "documentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [id: BigNumberish],
    [DocumentRegistry.DocumentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [fileHash: BytesLike, fileName: string, targetGroup: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [id: BigNumberish, fileHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DocumentRegistered"
  ): TypedContractEvent<
    DocumentRegisteredEvent.InputTuple,
    DocumentRegisteredEvent.OutputTuple,
    DocumentRegisteredEvent.OutputObject
  >;

  filters: {
    "DocumentRegistered(uint256,bytes32,string,string,address,uint256)": TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
    DocumentRegistered: TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
  };
}
