/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentRegistry } from "./DocumentRegistry";
export type { IRoleManagerDoc } from "./IRoleManagerDoc";
